apiVersion: apps/v1
kind: Deployment
metadata:
  name: gordon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gordon
  template:
    metadata:
      labels:
        app: gordon
    spec:
      containers:
        - name: gordon
          image: xerxes-y/gordon:latest
          # image: $DOCKER_USERNAME/gordon:$SEMAPHORE_WORKFLOW_ID
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/blog
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gordon
spec:
  selector:
    app: gordon
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
