springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
server:
  port: 8080
spring:
  application:
    name: Gordon-Ramsay
  data:
    mongodb:
      url: mongodb://mongodb:27017/kitchen
  webflux:
    problemdetails:
      enabled: true
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
logging:
  level:
    root: INFO
    web: DEBUG
    com.example: DEBUG
api:
  description: Hi i hope you enjoy checking our recipes ;)
  version : 01